# Generated by Django 4.1.7 on 2023-03-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_games_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
