# Generated by Django 4.1.7 on 2023-03-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_games_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='WIP', max_length=200),
        ),
    ]
